name: "Deploy"

on: 
  issue_comment:
    if: ${{github.event_name}}=="issue_comment"
    types: [created, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: "Get branch name and sha"
      id: get_branch
      run: |
        PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
        echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"
        echo "::set-output name=sha::$(echo $PR | jq -r '.head.sha')"

    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_branch.outputs.branch }}

    - run:  echo ${{github.event_name}}
