name: "Deploy"

on: 
  issue_comment:
    types: [created, edited]

jobs:
  deploy:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts    

    steps:
    - name: "Get branch name and sha"
      id: get_branch
      run: |
        PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
        echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"
        echo "::set-output name=sha::$(echo $PR | jq -r '.head.sha')"

    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_branch.outputs.branch }}

    - run: pwd
